import type { DetectionRule } from './engine.js';

export const DEFAULT_RULES: DetectionRule[] = [
  {
    id: 'ssh-brute-force',
    title: 'SSH Brute Force Detected',
    description: 'Multiple failed SSH login attempts from the same source',
    version: '1.0.0',
    category: 'auth',
    severity: 'high',
    source_types: ['ssh-guard', 'auth'],
    match: {
      field: 'message',
      operator: 'regex',
      value: 'failed ssh login|invalid ssh user',
    },
    threshold: 5,
    window_seconds: 300,
    cooldown_seconds: 600,
    tags: ['ssh', 'brute-force', 'credential-stuffing'],
    remediation: {
      action: 'block',
      ttl_seconds: 3600,
      description: 'Block source IP for 1 hour',
    },
    enabled: true,
  },
  {
    id: 'ssh-success-after-failures',
    title: 'SSH Login After Failed Attempts',
    description: 'Successful SSH login from an IP that had recent failures',
    version: '1.0.0',
    category: 'auth',
    severity: 'critical',
    source_types: ['ssh-guard', 'auth'],
    match: {
      field: 'message',
      operator: 'contains',
      value: 'SSH login accepted',
    },
    threshold: 1,
    window_seconds: 60,
    cooldown_seconds: 300,
    tags: ['ssh', 'compromise-indicator'],
    enabled: true,
  },
  {
    id: 'ssh-root-login',
    title: 'Root SSH Login Attempt',
    description: 'Direct root login via SSH detected',
    version: '1.0.0',
    category: 'auth',
    severity: 'high',
    source_types: ['ssh-guard', 'auth'],
    match: {
      field: 'message',
      operator: 'regex',
      value: '(failed|accepted).*\\broot\\b',
    },
    threshold: 1,
    window_seconds: 60,
    cooldown_seconds: 300,
    tags: ['ssh', 'root-access'],
    remediation: {
      action: 'block',
      ttl_seconds: 7200,
      description: 'Block source IP attempting root login',
    },
    enabled: true,
  },
  {
    id: 'ssh-user-enumeration',
    title: 'SSH User Enumeration',
    description: 'Multiple SSH attempts with different usernames from same source',
    version: '1.0.0',
    category: 'auth',
    severity: 'high',
    source_types: ['ssh-guard', 'auth'],
    match: {
      field: 'message',
      operator: 'contains',
      value: 'Invalid SSH user',
    },
    threshold: 3,
    window_seconds: 120,
    cooldown_seconds: 600,
    tags: ['ssh', 'enumeration', 'reconnaissance'],
    remediation: {
      action: 'block',
      ttl_seconds: 3600,
      description: 'Block source IP performing user enumeration',
    },
    enabled: true,
  },
  {
    id: 'sudo-abuse',
    title: 'Sudo Authentication Failure',
    description: 'Repeated sudo authentication failures',
    version: '1.0.0',
    category: 'auth',
    severity: 'high',
    source_types: ['user-journal', 'system'],
    match: {
      field: 'message',
      operator: 'regex',
      value: 'sudo.*authentication failure|sudo.*incorrect password|sudo.*FAILED',
    },
    threshold: 3,
    window_seconds: 300,
    cooldown_seconds: 600,
    tags: ['sudo', 'privilege-escalation'],
    enabled: true,
  },
  {
    id: 'web-sqli-attack',
    title: 'SQL Injection Attack Detected',
    description: 'HTTP request with SQL injection patterns',
    version: '1.0.0',
    category: 'web',
    severity: 'critical',
    source_types: ['log-watcher', 'web'],
    match: {
      field: 'message',
      operator: 'contains',
      value: 'Attack detected [SQLI]',
    },
    threshold: 1,
    window_seconds: 60,
    cooldown_seconds: 300,
    tags: ['web', 'sqli', 'injection'],
    remediation: {
      action: 'block',
      ttl_seconds: 3600,
      description: 'Block source IP performing SQL injection',
    },
    enabled: true,
  },
  {
    id: 'web-path-traversal',
    title: 'Path Traversal Attack Detected',
    description: 'HTTP request with path traversal patterns',
    version: '1.0.0',
    category: 'web',
    severity: 'critical',
    source_types: ['log-watcher', 'web'],
    match: {
      field: 'message',
      operator: 'contains',
      value: 'Attack detected [PATH_TRAVERSAL]',
    },
    threshold: 1,
    window_seconds: 60,
    cooldown_seconds: 300,
    tags: ['web', 'path-traversal', 'lfi'],
    remediation: {
      action: 'block',
      ttl_seconds: 3600,
      description: 'Block source IP performing path traversal',
    },
    enabled: true,
  },
  {
    id: 'web-xss-attack',
    title: 'XSS Attack Detected',
    description: 'HTTP request with cross-site scripting patterns',
    version: '1.0.0',
    category: 'web',
    severity: 'high',
    source_types: ['log-watcher', 'web'],
    match: {
      field: 'message',
      operator: 'regex',
      value: 'Attack detected \\[XSS\\]',
    },
    threshold: 1,
    window_seconds: 60,
    cooldown_seconds: 300,
    tags: ['web', 'xss', 'injection'],
    remediation: {
      action: 'block',
      ttl_seconds: 3600,
      description: 'Block source IP performing XSS attack',
    },
    enabled: true,
  },
  {
    id: 'web-scanner-detection',
    title: 'Web Vulnerability Scanner Detected',
    description: 'High volume of 4xx errors suggesting automated scanning',
    version: '1.0.0',
    category: 'web',
    severity: 'medium',
    source_types: ['log-watcher', 'web'],
    match: {
      field: 'message',
      operator: 'regex',
      value: 'Client error 4\\d{2}:',
    },
    threshold: 20,
    window_seconds: 60,
    cooldown_seconds: 600,
    tags: ['web', 'scanner', 'reconnaissance'],
    remediation: {
      action: 'block',
      ttl_seconds: 1800,
      description: 'Block automated scanner',
    },
    enabled: true,
  },
  {
    id: 'port-scan-indicator',
    title: 'Port Scan Indicators',
    description: 'Connection attempts to many ports from a single source',
    version: '1.0.0',
    category: 'network',
    severity: 'medium',
    source_types: ['network-monitor', 'network'],
    match: {
      field: 'message',
      operator: 'contains',
      value: 'port scan',
    },
    threshold: 1,
    window_seconds: 60,
    cooldown_seconds: 300,
    tags: ['network', 'port-scan', 'reconnaissance'],
    remediation: {
      action: 'block',
      ttl_seconds: 3600,
      description: 'Block port scanner',
    },
    enabled: true,
  },
  {
    id: 'system-critical-error',
    title: 'Critical System Error',
    description: 'Critical or emergency level system log message',
    version: '1.0.0',
    category: 'system',
    severity: 'critical',
    source_types: ['user-journal', 'system'],
    match: {
      field: 'severity',
      operator: 'equals',
      value: 'critical',
    },
    threshold: 1,
    window_seconds: 60,
    cooldown_seconds: 300,
    tags: ['system', 'critical'],
    enabled: true,
  },
  {
    id: 'exploit-probe-pattern',
    title: 'Exploit Probe Pattern',
    description: 'HTTP requests matching common exploit probe patterns',
    version: '1.0.0',
    category: 'web',
    severity: 'high',
    source_types: ['log-watcher', 'web'],
    match: {
      field: 'message',
      operator: 'regex',
      value: 'Attack detected \\[(CMD_INJECTION|RCE|SSRF|XXE)\\]',
    },
    threshold: 1,
    window_seconds: 60,
    cooldown_seconds: 300,
    tags: ['web', 'exploit', 'probe'],
    remediation: {
      action: 'block',
      ttl_seconds: 7200,
      description: 'Block source IP performing exploit probes',
    },
    enabled: true,
  },
];
