import { StyleSheet } from 'react-native';

export const s = StyleSheet.create({
  flex1: { flex: 1 },
  row: { flexDirection: 'row' },
  rowCenter: { flexDirection: 'row', alignItems: 'center' },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  wrap: { flexWrap: 'wrap' },
  center: { alignItems: 'center', justifyContent: 'center' },

  px4: { paddingHorizontal: 16 },
  px8: { paddingHorizontal: 32 },
  px3: { paddingHorizontal: 12 },
  py4: { paddingVertical: 16 },
  py3: { paddingVertical: 12 },
  py2: { paddingVertical: 8 },
  py8: { paddingVertical: 32 },
  pt2: { paddingTop: 8 },
  pb5: { paddingBottom: 20 },
  mb1: { marginBottom: 4 },
  mb2: { marginBottom: 8 },
  mb3: { marginBottom: 12 },
  mb4: { marginBottom: 16 },
  mb6: { marginBottom: 24 },
  mb8: { marginBottom: 32 },
  mb12: { marginBottom: 48 },
  mt1: { marginTop: 4 },
  mt2: { marginTop: 8 },
  mt4: { marginTop: 16 },
  mt8: { marginTop: 32 },
  mr4: { marginRight: 16 },

  card: { backgroundColor: '#111111', borderColor: '#222222', borderWidth: 1 },
  rounded: { borderRadius: 8 },
  roundedLg: { borderRadius: 12 },
  roundedFull: { borderRadius: 999 },
  overflowHidden: { overflow: 'hidden' },

  textDim: { color: '#666666' },
  textPrimary: { color: '#00ff41' },
  textMain: { color: '#e0e0e0' },
  textDanger: { color: '#ff4444' },
  textXs: { fontSize: 12 },
  textSm: { fontSize: 14 },
  textBase: { fontSize: 16 },
  textLg: { fontSize: 18 },
  fontBold: { fontWeight: '700' },
  fontSemi: { fontWeight: '600' },
  fontMono: { fontFamily: 'monospace' },

  h8: { height: 32 },
});
